tasks:
  - name: Docker compose up
    command: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
