version: '3.4'

services:

  order_php:
    build:
      target: api_platform_php_dev
    image: my_example_order_php_dev
    environment:
      XDEBUG_MODE: debug,coverage
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        idekey=PHPSTORM
      PHP_IDE_CONFIG: serverName=order
